### ISSUE TITLE
Create a full-page sign-in form

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Launcher#240]
In many business systems, it is not desired to load the app UI for an anonymous user.

There should be a setting (on the Settings page) to enable a full page sign-in form (which will be populated by the SignIn app, if it's running.

**Comment by miyconst** [comment]
This should be an issue for Dimitris when he comes. Assigning the issue on me for now.

**Comment by miyconst** [comment]
@Joltrix take a look at this issue. It should be an enhancement to the Launcher. 

The main idea is that Launcher should be able to request login to access any page, and setting to enable/disable this feature.

The actual page should be loaded once user signed in, and not loaded and then hidden by Launcher.

**Comment by miyconst** [comment]
Please create another branch from `master` and work there. Once done rise a pull request.

**Comment by warpech** [comment]
Moved to be responsibility of the Sign In app: https://github.com/StarcounterApps/SignIn/issues/89
