### ISSUE TITLE
Move Launcher's Launchpad to a new app

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Launcher#267]
We are splitting Launcher into separate apps (Website, WebsiteProvider, Launchpad, Search, Settings).

First and immediately useful step is to move Launchpad to a new app.

**Comment by per-samuelsson** [comment]
I really like this. For someone like me, it will be a lot easier to understand the role of those different modules if they separated into smaller, standalone apps.

**Comment by per-samuelsson** [comment]
And to still offer an experience similar to the one today, we could collectively refer to the as the "launcher suite" and possibly use meta packaging for those that would like to get started using them in the same fashion as monolithic launcher is used now.

**Comment by warpech** [comment]
@un-tone can you please take this? I have created a `Launchpad` repo for it.

Launchpad should only have one functionality - display icons provided from other apps. The best is when we start by extracting the exact functionality that is now implemented as part of Launcher.

**Comment by un-tone** [comment]
Created PRs https://github.com/StarcounterApps/Launcher/pull/275 and https://github.com/StarcounterApps/Launchpad/pull/1. Please review.

**Comment by un-tone** [comment]
Closing as done
