### ISSUE TITLE
Solution is not fully opened

### ISSUE THREAD

**Issue by TakhirMamirov** [StarcounterApps/Launcher#268]
Pulled the repo, tried to open entire solution in VS2015. The Launcher, and Launcher_AcceptanceHelperOne/Two projects are incompatible. How can I run them?

**Comment by warpech** [comment]
Are you sure that Starcounter extension to Visual Studio 2015 is properly installed?

For this, you need to shut down VS2015 while installing Starcounter. Then try to open Launcher.sln again

**Comment by Mackiovello** [comment]
@TakhirMamirov did you figure it out?

**Comment by TakhirMamirov** [comment]
Yes, long time ago :) Extension has not been installed automatically with no warning for that. I had to manually do that and all worked fine. Issue can be closed now.

**Comment by Mackiovello** [comment]
Great! Closing the issue
