### ISSUE TITLE
Refresh Launcher's testing infrastructure

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Launcher#277]
Launcher should use the same testing script and the same job template in TeamCity as KitchenSink.

Let's not overdo it, because Launcher is being phased out as an app. But it is important that all projects in TeamCity follow the same config.

Part of: https://github.com/Starcounter/AdminTrack/issues/261

**Comment by warpech** [comment]
@KmaTTi89 pls close this when Launcher's build status is presented in GitHub.

**Comment by KmaTTi89** [comment]
@warpech 
Build status is not presented in GitHub not because changes I made.
This is an error for KitchenSink, nothing was changed in commit status publisher:

> Publish status error in build #563 {build id=21132, buildTypeId=Apps_KitchenSinkTestsDevelop}: java.io.IOException: Failed to complete request to GitHub. Status: HTTP/1.1 307 Temporary Redirect

This is the error for Launcher:

> Publish status error in build #104 {build id=21170, buildTypeId=Apps_Launcher_LauncherTestDevelop}: java.io.IOException: Failed to complete request to GitHub. Status: HTTP/1.1 401 Unauthorized

I think GitHub API was changed and we need to update TeamCity. New version is available.

**Comment by warpech** [comment]
I will create a new issue in AdminTrack then.

**Comment by KmaTTi89** [comment]
New TC version fix this issue. From changelog:
TW-48015 - Few issues with reporting Commit Status Publisher errors to the server log
TW-45475 - Commit Status Publisher not reporting build status on merge requests on GitLab

So waiting for updated

**Comment by KmaTTi89** [comment]
Done
