### ISSUE TITLE
Use uniform batch scripts

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Launcher#279]
Use uniform batch scripts as presented in https://starcounter.gitbooks.io/guidelines/content/batch-files.html

Discussion: https://github.com/Starcounter/Guidelines/issues/6

**Comment by KmaTTi89** [comment]
@warpech Done in https://github.com/StarcounterApps/Launcher/pull/280

**Comment by KmaTTi89** [comment]
Done in https://github.com/StarcounterApps/Launcher/pull/283
