### ISSUE TITLE
Search does not work well

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Launcher#285]
### Steps to reproduce

1. Start Launcher, People (both develop branch)
2. Go to localhost:8080/launcher
3. Type "aha" in the search field
4. Press OK

### Expected result

You should be redirected to a search result page

### Actual result

A 404 error shows up

##### Browsers affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot

![2017-03-28 21_44_32-launcher](https://cloud.githubusercontent.com/assets/566463/24424211/16fbce86-1400-11e7-9f7b-32fcaae9a194.png)

**Comment by un-tone** [comment]
Closing as done
